language: python

python:
  - "3.5"
  - "3.6"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - coverage run test.py
  - codecov
